// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/card.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	model "github.com/bayu-gara/cards/internal/domain/model"
	gomock "github.com/golang/mock/gomock"
)

// MockCardRepository is a mock of CardRepository interface.
type MockCardRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCardRepositoryMockRecorder
}

// MockCardRepositoryMockRecorder is the mock recorder for MockCardRepository.
type MockCardRepositoryMockRecorder struct {
	mock *MockCardRepository
}

// NewMockCardRepository creates a new mock instance.
func NewMockCardRepository(ctrl *gomock.Controller) *MockCardRepository {
	mock := &MockCardRepository{ctrl: ctrl}
	mock.recorder = &MockCardRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCardRepository) EXPECT() *MockCardRepositoryMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockCardRepository) FindAll(ctx context.Context) ([]model.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]model.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockCardRepositoryMockRecorder) FindAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockCardRepository)(nil).FindAll), ctx)
}

// FindByCode mocks base method.
func (m *MockCardRepository) FindByCode(ctx context.Context, code string) (model.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCode", ctx, code)
	ret0, _ := ret[0].(model.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCode indicates an expected call of FindByCode.
func (mr *MockCardRepositoryMockRecorder) FindByCode(ctx, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCode", reflect.TypeOf((*MockCardRepository)(nil).FindByCode), ctx, code)
}

// FindByCodes mocks base method.
func (m *MockCardRepository) FindByCodes(ctx context.Context, codes []string) ([]model.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCodes", ctx, codes)
	ret0, _ := ret[0].([]model.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCodes indicates an expected call of FindByCodes.
func (mr *MockCardRepositoryMockRecorder) FindByCodes(ctx, codes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCodes", reflect.TypeOf((*MockCardRepository)(nil).FindByCodes), ctx, codes)
}

// Insert mocks base method.
func (m *MockCardRepository) Insert(ctx context.Context, card model.Card) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, card)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockCardRepositoryMockRecorder) Insert(ctx, card interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockCardRepository)(nil).Insert), ctx, card)
}
