// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/database/database.go

// Package database is a generated GoMock package.
package database

import (
	sql "database/sql"
	reflect "reflect"

	config "github.com/bayu-gara/cards/pkg/config"
	gomock "github.com/golang/mock/gomock"
)

// MockSQLConnector is a mock of SQLConnector interface.
type MockSQLConnector struct {
	ctrl     *gomock.Controller
	recorder *MockSQLConnectorMockRecorder
}

// MockSQLConnectorMockRecorder is the mock recorder for MockSQLConnector.
type MockSQLConnectorMockRecorder struct {
	mock *MockSQLConnector
}

// NewMockSQLConnector creates a new mock instance.
func NewMockSQLConnector(ctrl *gomock.Controller) *MockSQLConnector {
	mock := &MockSQLConnector{ctrl: ctrl}
	mock.recorder = &MockSQLConnectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQLConnector) EXPECT() *MockSQLConnectorMockRecorder {
	return m.recorder
}

// Connect mocks base method.
func (m *MockSQLConnector) Connect(cfg config.DatabaseConfig) (*sql.DB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", cfg)
	ret0, _ := ret[0].(*sql.DB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Connect indicates an expected call of Connect.
func (mr *MockSQLConnectorMockRecorder) Connect(cfg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockSQLConnector)(nil).Connect), cfg)
}
