// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/deck/deck.go

// Package deck is a generated GoMock package.
package deck

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// CreateDeck mocks base method.
func (m *MockUsecase) CreateDeck(ctx context.Context, shuffle bool, cards []string) (Deck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDeck", ctx, shuffle, cards)
	ret0, _ := ret[0].(Deck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDeck indicates an expected call of CreateDeck.
func (mr *MockUsecaseMockRecorder) CreateDeck(ctx, shuffle, cards interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDeck", reflect.TypeOf((*MockUsecase)(nil).CreateDeck), ctx, shuffle, cards)
}

// DrawCard mocks base method.
func (m *MockUsecase) DrawCard(ctx context.Context, deckID string, count int) (Deck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DrawCard", ctx, deckID, count)
	ret0, _ := ret[0].(Deck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DrawCard indicates an expected call of DrawCard.
func (mr *MockUsecaseMockRecorder) DrawCard(ctx, deckID, count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DrawCard", reflect.TypeOf((*MockUsecase)(nil).DrawCard), ctx, deckID, count)
}

// OpenDeck mocks base method.
func (m *MockUsecase) OpenDeck(ctx context.Context, deckID string) (Deck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenDeck", ctx, deckID)
	ret0, _ := ret[0].(Deck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenDeck indicates an expected call of OpenDeck.
func (mr *MockUsecaseMockRecorder) OpenDeck(ctx, deckID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenDeck", reflect.TypeOf((*MockUsecase)(nil).OpenDeck), ctx, deckID)
}
